# Generated by Django 5.0.1 on 2024-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_started',
            field=models.DateField(help_text='День когда задача должна начаться'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(help_text='День когда задача должна быть выполнена'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='task details'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='DEFAULT TITLE!!!', max_length=75),
        ),
    ]
