# Generated by Django 5.0.1 on 2024-01-12 11:18

import apps.todo.models_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_date_started_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=apps.todo.models_helpers.create_default_description, max_length=1500, verbose_name='task details'),
        ),
    ]
