# Generated by Django 5.0.1 on 2024-01-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='DEFAULT TITLE!!!', max_length=75, unique=True),
        ),
    ]
